# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3bddfbe2e8f96dc48574f5cb2a0f1bad"
name = "LM Sticky Cart Drawer & Upsell"
application_url = "https://addtostickycart.luckimediadevelopment.com/"
embedded = true

[access_scopes]
scopes = "read_products,read_themes,write_content,write_pixels,read_customer_events"

[build]
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://addtostickycart.luckimediadevelopment.com/authenticate"
]

[webhooks]
api_version = "2023-01"

[pos]
embedded = false
