const TemplateStyle = {
  add_to_cart_sticky: false,
  default_template: 2,
  current_template: {
    general_settings: {
      desktop: true,
      mobile: false,
      font_family: "Roboto",
      font_size: 20,
      font_bold: false,
      font_italic: false,
      font_underline: false,
      font_title_color: "rgba(0, 255, 0, 1)",
      font_height: 70,
      font_price_color: "rgba(1, 0, 255, 1)",
      font_bg_color: "rgba(255, 1, 0, 0)",
    },
    buy_btn_settings: {
      edit_text: "BUY NOW1",
      sold_out: "Sold out",
      unavailable: "Unavailable",
      btn_height: 30,
      btn_width: 120,
      btn_size: 20,
      btn_bold: false,
      btn_italic: false,
      btn_underline: false,
      btn_text_color: "rgba(0, 255, 1, 1)",
      btn_bg_color: "rgba(0, 154, 0, 1)",
      btn_text_hover_color: "rgba(0, 1, 143, 0)",
      btn_bg_hover_color: "rgba(0, 123, 1, 1)",
      btn_border: 1,
      btn_border_radius: 1,
      btn_border_color: "rgba(1, 187, 1, 0)",
      btn_border_hover_color: "rgba(0, 222, 0, 1)",
    },
  },
  template_1: {
    general_settings: {
      desktop: true,
      mobile: false,
      font_family: "Roboto",
      font_size: 20,
      font_bold: false,
      font_italic: false,
      font_underline: false,
      font_title_color: "rgba(0, 0, 0, 1)",
      font_height: 70,
      font_price_color: "rgba(0, 0, 0, 1)",
      font_bg_color: "rgba(0, 0, 0, 0)",
    },
    buy_btn_settings: {
      edit_text: "BUY NOW1",
      sold_out: "Sold out",
      unavailable: "Unavailable",
      btn_height: 30,
      btn_width: 120,
      btn_size: 20,
      btn_bold: false,
      btn_italic: false,
      btn_underline: false,
      btn_text_color: "rgba(0, 0, 0, 1)",
      btn_bg_color: "rgba(0, 0, 0, 0)",
      btn_text_hover_color: "rgba(0, 0, 0, 0)",
      btn_bg_hover_color: "rgba(0, 0, 0, 1)",
      btn_border: 1,
      btn_border_radius: 1,
      btn_border_color: "rgba(0, 0, 0, 0)",
      btn_border_hover_color: "rgba(0, 0, 0, 0)",
    },
  },
  template_2: {
    general_settings: {
      desktop: true,
      mobile: false,
      font_family: "Roboto",
      font_size: 20,
      font_bold: false,
      font_italic: false,
      font_underline: false,
      font_title_color: "rgba(0, 0, 0, 1)",
      font_height: 70,
      font_price_color: "rgba(0, 0, 0, 1)",
      font_bg_color: "rgba(0, 0, 0, 0)",
    },
    buy_btn_settings: {
      edit_text: "BUY NOW2",
      sold_out: "Sold out",
      unavailable: "Unavailable",
      btn_height: 30,
      btn_width: 120,
      btn_size: 20,
      btn_bold: false,
      btn_italic: false,
      btn_underline: false,
      btn_text_color: "rgba(0, 0, 0, 1)",
      btn_bg_color: "rgba(0, 0, 0, 0)",
      btn_text_hover_color: "rgba(0, 0, 0, 0)",
      btn_bg_hover_color: "rgba(0, 0, 0, 1)",
      btn_border: 1,
      btn_border_radius: 1,
      btn_border_color: "rgba(0, 0, 0, 0)",
      btn_border_hover_color: "rgba(0, 0, 0, 0)",
    },
  },
  template_3: {
    general_settings: {
      desktop: true,
      mobile: false,
      font_family: "Roboto",
      font_size: 20,
      font_bold: false,
      font_italic: false,
      font_underline: false,
      font_title_color: "rgba(0, 0, 0, 1)",
      font_height: 70,
      font_price_color: "rgba(0, 0, 0, 1)",
      font_bg_color: "rgba(0, 0, 0, 0)",
    },
    buy_btn_settings: {
      edit_text: "BUY NOW3",
      sold_out: "Sold out",
      unavailable: "Unavailable",
      btn_height: 30,
      btn_width: 120,
      btn_size: 20,
      btn_bold: false,
      btn_italic: false,
      btn_underline: false,
      btn_text_color: "rgba(0, 0, 0, 1)",
      btn_bg_color: "rgba(0, 0, 0, 0)",
      btn_text_hover_color: "rgba(0, 0, 0, 0)",
      btn_bg_hover_color: "rgba(0, 0, 0, 1)",
      btn_border: 1,
      btn_border_radius: 1,
      btn_border_color: "rgba(0, 0, 0, 0)",
      btn_border_hover_color: "rgba(0, 0, 0, 0)",
    },
  },
  template_4: {
    general_settings: {
      desktop: true,
      mobile: false,
      font_family: "Roboto",
      font_size: 20,
      font_bold: false,
      font_italic: false,
      font_underline: false,
      font_title_color: "rgba(0, 0, 0, 1)",
      font_height: 70,
      font_price_color: "rgba(0, 0, 0, 1)",
      font_bg_color: "rgba(0, 0, 0, 0)",
    },
    buy_btn_settings: {
      edit_text: "BUY NOW4",
      sold_out: "Sold out",
      unavailable: "Unavailable",
      btn_height: 30,
      btn_width: 120,
      btn_size: 20,
      btn_bold: false,
      btn_italic: false,
      btn_underline: false,
      btn_text_color: "rgba(0, 0, 0, 1)",
      btn_bg_color: "rgba(0, 0, 0, 0)",
      btn_text_hover_color: "rgba(0, 0, 0, 0)",
      btn_bg_hover_color: "rgba(0, 0, 0, 1)",
      btn_border: 1,
      btn_border_radius: 1,
      btn_border_color: "rgba(0, 0, 0, 0)",
      btn_border_hover_color: "rgba(0, 0, 0, 0)",
    },
  },
};

export default TemplateStyle;
