<?php
return [
    'general_settings' => [
        'checkDesktop' => true,
        'checkMobile' => false,
        'gsFontFamily' => 'PT Sans',
        'gsFontsize' => 16,
        'gsPriceFontsize' => 14,
        'gsBold' => true,
        'gsItalic' => false,
        'gsUnderline' => false,
        'gsTitleColor' => '#000000',
        'containerHeight' => 90,
        'gsPriceColor' => '#000000',
        'gsBgColor' => '#ffffff',
        'position' => 'Top',
        'gsOffsetValue' => '0',
        'gsAction' => '1',
        'gsDisplayCondition' => '1',
        "gsNotificationBarText" => "Great news! Here's something special for you!",
        "gsNotificationBarItalic" => true,
        "gsNotificationBarBold" => true,
        "gsNotificationBarItalic" => true,
        "gsNotificationBarBold" => true,
        "gsNotificationBarTextColor" => true,
        "gsNotificationBarBold" => true
    ],
    'buy_btn_settings' => [
        'editText' => 'ADD TO CART',
        // 'soldOut'=> "Sold out",
        'unavailable' => 'SOLD',
        'btnheightValue' => 90,
        'btnWidthValue' => 150,
        'btnFontsize' => 16,
        'btnBold' => true,
        'btnItalic' => false,
        'btnUnderline' => false,
        'btnTextColor' => '#ffffff',
        'btnBgColor' => '#000000',
        'btnTexthoverColor' => '#9B9B9B',
        'btnBgHoverColor' => '#252525',
        'btnBorderThickness' => 0,
        'btnBorderRadius' => 0,
        'btnBorderColor' => '#000000',
        'btnBorderHoverColor' => '#000000',
    ],
];
