<?php
return [
    'action' => '1',
    'btnSize' => 50,
    'bgColor' => '#000000',
    'bgHoverColor' => '#808080',
    'borderSize' => 0,
    'borderColor' => '#000000',
    'borderHoverColor' => '#000000',
    'positionTop' => 25,
    // 'positionBottom' => 0,
    'positionLeft' => 96,
    // 'positionRight' => 0,
    'iconSize' => 20,
    'iconColor' => '#FFFFFF',
    'iconHoverColor' => '#E6E6E6',
    'enableCount' => true,
    'numberCount' => 8,
    'countSize' => 16,
    'countFontSize' => 16,
    'countColor' => '#000000',
    'countHoverColor' => '#000000',
    'countBgColor' => '#FFFFFF',
    'countBgHoverColor' => '#E6E6E6',
];
