<?php
return [
    'action' => '1',
    'btnSize' => 50,
    'bgColor' => '#000000',
    'bgHoverColor' => '#808080',
    'borderSize' => 1,
    'borderColor' => '#000000',
    'borderHoverColor' => '#000000',
    'positionTop' => 0,
    // 'positionBottom' => 30,
    'positionLeft' => 0,
    // 'positionRight' => 0,
    'iconSize' => 20,
    'iconColor' => '#FFFFFF',
    'iconHoverColor' => '#E6E6E6',
    'enableCount' => true,
    'numberCount' => 8,
    'countSize' => 14,
    'countFontSize' => 14,
    'countColor' => '#000000',
    'countHoverColor' => '#000000',
    'countBgColor' => '#FFFFFF',
    'countBgHoverColor' => '#E6E6E6',
];
