<?php
return array(
    'enable'=> false,
    'defaultTemplate'=> 2,
    'general_settings'=> [
        'checkDesktop'=> true,
        'checkMobile'=> false,
        'gsFontFamily'=> "Fira Sans",
        'gsFontsize'=> 16,
        'gsBold'=> true,
        'gsItalic'=> false,
        'gsUnderline'=> false,
        'gsTitleColor'=> "#fff",
        'containerHeight'=> 60,
        'gsPriceColor'=> "#ccc",
        'gsBgColor'=> "#333",
        'position'=> "Top",
        'gsOffsetValue'=> "00",
        'gsAction'=> "1",
        'gsDisplayCondition'=> "1",
    ],
      'buy_btn_settings'=> [
        'editText'=> "BUY NOW1",
        'soldOut'=> "Sold out",
        'unavailable'=> "Unavailable",
        'btnheightValue'=> 60,
        'btnWidthValue'=> 150,
        'btnFontsize'=> 16,
        'btnBold'=> true,
        'btnItalic'=> false,
        'btnUnderline'=> false,
        'btnTextColor'=> "#fff",
        'btnBgColor'=> "#FF9138",
        'btnTexthoverColor'=> "#FF9138",
        'btnBgHoverColor'=> "#fff",
        'btnBorderThickness'=> 0,
        'btnBorderRadius'=> 0,
        'btnBorderColor'=> "#FF9138",
        'btnBorderHoverColor'=> "#FF9138",
    ],
);