<?php
return array(
    'general_settings'=> [
        'checkDesktop'=> true,
        'checkMobile'=> false,
        'gsFontFamily'=> "PT Sans",
        'gsFontsize'=> 16,
        'gsBold'=> false,
        'gsItalic'=> false,
        'gsUnderline'=> false,
        'gsTitleColor'=> "rgba(0, 0, 0, 1)",
        'containerHeight'=> 70,
        'gsPriceColor'=> "rgba(0, 0, 0, 1)",
        'gsBgColor'=> "rgba(242, 108, 79, 1)",
        'position'=> "Top",
        'gsOffsetValue'=> "10",
        'gsAction'=> "1",
        'gsDisplayCondition'=> "1",
      ],
      'buy_btn_settings'=> [
        'editText'=> "BUY NOW",
        // 'soldOut'=> "Sold out",
        'unavailable'=> "Unavailable",
        'btnheightValue'=> 70,
        'btnWidthValue'=> 150,
        'btnFontsize'=> 16,
        'btnBold'=> true,
        'btnItalic'=> false,
        'btnUnderline'=> false,
        'btnTextColor'=> "rgba(255, 255, 255, 1)",
        'btnBgColor'=> "rgba(0, 0, 0, 1)",
        'btnTexthoverColor'=> "rgba(155,155,155, 1)",
        'btnBgHoverColor'=> "rgba(37,37,37, 1)",
        'btnBorderThickness'=> 0,
        'btnBorderRadius'=> 0,
        'btnBorderColor'=> "rgba(0, 0, 0, 1)",
        'btnBorderHoverColor'=> "rgba(0, 0, 0, 1)",
      ],
);