<?php
return [
    'general_settings' => [
        'checkDesktop' => true,
        'checkMobile' => false,
        'gsFontFamily' => 'PT Sans',
        'gsFontsize' => 16,
        'gsPriceFontsize' => 16,
        'gsBold' => false,
        'gsItalic' => false,
        'gsUnderline' => false,
        'gsTitleColor' => '#000000',
        'containerHeight' => 70,
        'gsPriceColor' => '#000000',
        'gsBgColor' => '#ffffff',
        'position' => 'Top',
        'gsOffsetValue' => '0',
        'gsAction' => '1',
        'gsDisplayCondition' => '1',
    ],
    'buy_btn_settings' => [
        'editText' => 'BUY NOW',
        // 'soldOut'=> "Sold out",
        'unavailable' => 'Unavailable',
        'btnheightValue' => 35,
        'btnWidthValue' => 150,
        'btnFontsize' => 14,
        'btnBold' => false,
        'btnItalic' => false,
        'btnUnderline' => false,
        'btnTextColor' => '#ffffff',
        'btnBgColor' => '#ff9138',
        'btnTexthoverColor' => '#9b9b9b',
        'btnBgHoverColor' => '#fd8522',
        'btnBorderThickness' => 0,
        'btnBorderRadius' => 50,
        'btnBorderColor' => '#ff9138',
        'btnBorderHoverColor' => '#ff9138',
    ],
];
