<?php
return array(
    'general_settings'=> [
        'checkDesktop'=> true,
        'checkMobile'=> false,
        'gsFontFamily'=> "PT Sans",
        'gsFontsize'=> 16,
        'gsPriceFontsize'=> 14,
        'gsBold'=> false,
        'gsItalic'=> false,
        'gsUnderline'=> false,
        'gsTitleColor'=> "rgba(0, 0, 0, 1)",
        'containerHeight'=> 70,
        'gsPriceColor'=> "rgba(0, 0, 0, 1)",
        'gsBgColor'=> "rgba(255, 255, 255, 1)",
        'position'=> "Top",
        'gsOffsetValue'=> "00",
        'gsAction'=> "1",
        'gsDisplayCondition'=> "1",
    ],
    'buy_btn_settings'=> [
        'editText'=> "BUY NOW",
        // 'soldOut'=> "Sold out",
        'unavailable'=> "Unavailable",
        'btnheightValue'=> 35,
        'btnWidthValue'=> 150,
        'btnFontsize'=> 14,
        'btnBold'=> false,
        'btnItalic'=> false,
        'btnUnderline'=> false,
        'btnTextColor'=> "rgba(255, 255, 255, 1)",
        'btnBgColor'=> "rgba(255, 145, 56, 1)",
        'btnTexthoverColor'=> "rgba(155,155,155, 1)",
        'btnBgHoverColor'=> "rgba(253, 133, 34, 1)",
        'btnBorderThickness'=> 0,
        'btnBorderRadius'=> 50,
        'btnBorderColor'=> "rgba(255, 145, 56, 1)",
        'btnBorderHoverColor'=> "rgba(255, 145, 56, 1)",
    ],
);