<?php
return array(
        'general_settings'=> [
            'checkDesktop'=> true,
            'checkMobile'=> false,
            'gsFontFamily'=> "Fira Sans",
            'gsFontsize'=> 20,
            'gsBold'=> true,
            'gsItalic'=> true,
            'gsUnderline'=> true,
            'gsTitleColor'=> "rgba(51, 51, 51, 1)",
            'containerHeight'=> 70,
            'gsPriceColor'=> "rgba(0, 0, 0, 1)",
            'gsBgColor'=> "rgba(243, 243, 243, 1)",
            'position'=> "Top",
            'gsOffsetValue'=> "50",
            'gsAction'=> "1",
            'gsDisplayCondition'=> "1",
    ],
        'buy_btn_settings'=> [
            'editText'=> "BUY NOW",
            // 'soldOut'=> "Sold out",
            'unavailable'=> "Unavailable",
            'btnheightValue'=> 35,
            'btnWidthValue'=> 150,
            'btnFontsize'=> 16,
            'btnBold'=> false,
            'btnItalic'=> false,
            'btnUnderline'=> false,
            'btnTextColor'=> "rgba(255, 255, 255, 1)",
            'btnBgColor'=> "rgba(51, 51, 51, 1)",
            'btnTexthoverColor'=> "rgba(51, 51, 51, 1)",
            'btnBgHoverColor'=> "rgba(255, 255, 255, 1)",
            'btnBorderThickness'=> 2,
            'btnBorderRadius'=> 15,
            'btnBorderColor'=> "rgba(1, 187, 1, 0)",
            'btnBorderHoverColor'=> "rgba(255, 255, 255, 1)",
    ],
);