<?php
return array(
    'add_to_cart_sticky'=> false,
    'default_template'=> 2,
    'general_settings'=> [
        'desktop'=> true,
        'mobile'=> false,
        'font_family'=> "Fira Sans",
        'font_size'=> 16,
        'font_bold'=> true,
        'font_italic'=> false,
        'font_underline'=> false,
        'font_title_color'=> "#fff",
        'font_height'=> 60,
        'font_price_color'=> "#ccc",
        'font_bg_color'=> "#333",
        'position'=> "Top",
        'offset'=> "00",
        'action'=> "1",
        'display_condition'=> "1",
    ],
    'buy_btn_settings'=> [
        'edit_text'=> "BUY NOW1",
        'sold_out'=> "Sold out",
        'unavailable'=> "Unavailable",
        'btn_height'=> 60,
        'btn_width'=> 150,
        'btn_size'=> 16,
        'btn_bold'=> true,
        'btn_italic'=> false,
        'btn_underline'=> false,
        'btn_text_color'=> "#fff",
        'btn_bg_color'=> "#FF9138",
        'btn_text_hover_color'=> "#FF9138",
        'btn_bg_hover_color'=> "#fff",
        'btn_border'=> 0,
        'btn_border_radius'=> 0,
        'btn_border_color'=> "#FF9138",
        'btn_border_hover_color'=> "#FF9138",
    ],
);