<?php
return array(
        'enable'=> false,
        'defaultTemplate'=> 2,
        'general_settings'=> [
            'checkDesktop'=> true,
            'checkMobile'=> false,
            'gsFontFamily'=> "Fira Sans",
            'gsFontsize'=> 20,
            'gsBold'=> true,
            'gsItalic'=> true,
            'gsUnderline'=> true,
            'gsTitleColor'=> "#333",
            'containerHeight'=> 70,
            'gsPriceColor'=> "#000",
            'gsBgColor'=> "#f3f3f3",
            'position'=> "Top",
            'gsOffsetValue'=> "50",
            'gsAction'=> "1",
            'gsDisplayCondition'=> "1",
    ],
        'buy_btn_settings'=> [
            'editText'=> "BUY NOW",
            'soldOut'=> "Sold out",
            'unavailable'=> "Unavailable",
            'btnheightValue'=> 35,
            'btnWidthValue'=> 150,
            'btnFontsize'=> 16,
            'btnBold'=> false,
            'btnItalic'=> false,
            'btnUnderline'=> false,
            'btnTextColor'=> "#fff",
            'btnBgColor'=> "#333",
            'btnTexthoverColor'=> "#333",
            'btnBgHoverColor'=> "#fff",
            'btnBorderThickness'=> 2,
            'btnBorderRadius'=> 15,
            'btnBorderColor'=> "rgba(1, 187, 1, 0)",
            'btnBorderHoverColor'=> "#fff",
    ],
);