<?php
return array(
    'enable'=> false,
    'defaultTemplate'=> 2,
    'general_settings'=> [
        'checkDesktop'=> true,
        'checkMobile'=> false,
        'gsFontFamily'=> "Fira Sans",
        'gsFontsize'=> 16,
        'gsBold'=> true,
        'gsItalic'=> false,
        'gsUnderline'=> false,
        'gsTitleColor'=> "#333",
        'containerHeight'=> 70,
        'gsPriceColor'=> "#000",
        'gsBgColor'=> "#f3f3f3",
        'position'=> "Top",
        'gsOffsetValue'=> "00",
        'gsAction'=> "1",
        'gsDisplayCondition'=> "1",
    ],
    'buy_btn_settings'=> [
        'editText'=> "BUY NOW1",
        'soldOut'=> "Sold out",
        'unavailable'=> "Unavailable",
        'btnheightValue'=> 28,
        'btnWidthValue'=> 100,
        'btnFontsize'=> 12,
        'btnBold'=> true,
        'btnItalic'=> false,
        'btnUnderline'=> false,
        'btnTextColor'=> "#fff",
        'btnBgColor'=> "#333",
        'btnTexthoverColor'=> "#333",
        'btnBgHoverColor'=> "#FF9138",
        'btnBorderThickness'=> 1,
        'btnBorderRadius'=> 15,
        'btnBorderColor'=> "#FF9138",
        'btnBorderHoverColor'=> "#FF9138",
    ],
);