<?php
return array(
    'general_settings'=> [
        'checkDesktop'=> true,
        'checkMobile'=> false,
        'gsFontFamily'=> "Fira Sans",
        'gsFontsize'=> 16,
        'gsBold'=> true,
        'gsItalic'=> false,
        'gsUnderline'=> false,
        'gsTitleColor'=> "rgba(51, 51, 51, 1)",
        'containerHeight'=> 70,
        'gsPriceColor'=> "rgba(0, 0, 0, 1)",
        'gsBgColor'=> "rgba(243, 243, 243, 1)",
        'position'=> "Top",
        'gsOffsetValue'=> "00",
        'gsAction'=> "1",
        'gsDisplayCondition'=> "1",
    ],
    'buy_btn_settings'=> [
        'editText'=> "BUY NOW1",
        'soldOut'=> "Sold out",
        'unavailable'=> "Unavailable",
        'btnheightValue'=> 28,
        'btnWidthValue'=> 100,
        'btnFontsize'=> 12,
        'btnBold'=> true,
        'btnItalic'=> false,
        'btnUnderline'=> false,
        'btnTextColor'=> "rgba(255, 255, 255, 1)",
        'btnBgColor'=> "rgba(51, 51, 51, 1)",
        'btnTexthoverColor'=> "rgba(51, 51, 51, 1)",
        'btnBgHoverColor'=> "rgba(255, 145, 56, 1)",
        'btnBorderThickness'=> 1,
        'btnBorderRadius'=> 15,
        'btnBorderColor'=> "rgba(255, 145, 56, 1)",
        'btnBorderHoverColor'=> "rgba(255, 145, 56, 1)",
    ],
);